# Generated by Django 5.2.17 on 2026-10-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Redemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="卡密"),
                ),
                (
                    "product_code",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="软件标识"
                    ),
                ),
                ("redeemed_at", models.DateTimeField(verbose_name="核销时间")),
            ],
            options={
                "verbose_name": "核销记录",
                "verbose_name_plural": "核销记录",
                "ordering": ["-redeemed_at", "-id"],
            },
        ),
    ]
