# Generated by Django 5.2.17 on 2026-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redeem", "0002_redemption_seq_uses"),
    ]

    operations = [
        migrations.AddField(
            model_name="redemption",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="核销 IP"
            ),
        ),
    ]
