# Generated by Django 5.2.17 on 2026-10-05 11:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="卡密"),
                ),
                (
                    "product_code",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="软件标识"
                    ),
                ),
                (
                    "device_hash",
                    models.CharField(max_length=64, verbose_name="设备指纹"),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="设备信息"
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="有效时长（天）",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="到期时间")),
                ("disabled", models.BooleanField(default=False, verbose_name="禁用")),
                ("activated_at", models.DateTimeField(verbose_name="激活时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "激活记录",
                "verbose_name_plural": "激活记录",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_device_hash",
                    models.CharField(max_length=64, verbose_name="旧设备指纹"),
                ),
                (
                    "old_device_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="旧设备信息"
                    ),
                ),
                (
                    "new_device_hash",
                    models.CharField(max_length=64, verbose_name="新设备指纹"),
                ),
                (
                    "new_device_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="新设备信息"
                    ),
                ),
                (
                    "penalty_hours",
                    models.PositiveIntegerField(verbose_name="扣减时长（小时）"),
                ),
                (
                    "expires_before",
                    models.DateTimeField(verbose_name="换设备前到期时间"),
                ),
                (
                    "expires_after",
                    models.DateTimeField(verbose_name="换设备后到期时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="换设备时间"
                    ),
                ),
                (
                    "activation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_logs",
                        to="activation.activation",
                        verbose_name="激活记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "换设备记录",
                "verbose_name_plural": "换设备记录",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
