# Generated by Django 5.2.17 on 2026-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="激活 IP"
            ),
        ),
        migrations.AddField(
            model_name="transferlog",
            name="new_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="新设备激活 IP"
            ),
        ),
    ]
