# Generated by Django 5.2.17 on 2026-10-05 11:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=64, unique=True, verbose_name="标识"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="名称")),
                (
                    "allow_transfer",
                    models.BooleanField(default=False, verbose_name="允许换设备"),
                ),
                (
                    "transfer_penalty_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="换设备扣减时长（小时）"
                    ),
                ),
                ("disabled", models.BooleanField(default=False, verbose_name="禁用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "软件（product）",
                "verbose_name_plural": "软件（product）",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="批次标识"
                    ),
                ),
                ("secret", models.CharField(max_length=32, verbose_name="批次随机值")),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="卡密有效时长（天）",
                    ),
                ),
                ("count", models.PositiveIntegerField(verbose_name="生成数量")),
                ("disabled", models.BooleanField(default=False, verbose_name="禁用")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="生成时间"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="keys.product",
                        verbose_name="所属软件",
                    ),
                ),
            ],
            options={
                "verbose_name": "卡密批次",
                "verbose_name_plural": "卡密批次",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
