# Generated by Django 5.2.17 on 2026-09-28 20:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LicenseKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=128, unique=True, verbose_name="key"),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="有效时长（天）",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="到期时间"
                    ),
                ),
                ("disabled", models.BooleanField(default=False, verbose_name="禁用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "key",
                "verbose_name_plural": "key",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=64, unique=True, verbose_name="标识"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="名称")),
                (
                    "allow_transfer",
                    models.BooleanField(default=False, verbose_name="允许换设备"),
                ),
                (
                    "transfer_penalty_hours",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 表示换设备不扣除时长；1 天填 24",
                        verbose_name="换设备扣减时长（小时）",
                    ),
                ),
                ("disabled", models.BooleanField(default=False, verbose_name="禁用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "软件（product）",
                "verbose_name_plural": "软件（product）",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Activation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_hash",
                    models.CharField(max_length=64, verbose_name="设备指纹"),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="设备信息"
                    ),
                ),
                ("activated_at", models.DateTimeField(verbose_name="绑定时间")),
                (
                    "key",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation",
                        to="keys.licensekey",
                        verbose_name="key",
                    ),
                ),
            ],
            options={
                "verbose_name": "当前激活记录",
                "verbose_name_plural": "当前激活记录",
            },
        ),
        migrations.AddField(
            model_name="licensekey",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="keys",
                to="keys.product",
                verbose_name="所属软件",
            ),
        ),
        migrations.CreateModel(
            name="TransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_device_hash",
                    models.CharField(max_length=64, verbose_name="旧设备指纹"),
                ),
                (
                    "old_device_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="旧设备信息"
                    ),
                ),
                (
                    "new_device_hash",
                    models.CharField(max_length=64, verbose_name="新设备指纹"),
                ),
                (
                    "new_device_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="新设备信息"
                    ),
                ),
                (
                    "penalty_hours",
                    models.PositiveIntegerField(verbose_name="扣减时长（小时）"),
                ),
                (
                    "expires_before",
                    models.DateTimeField(verbose_name="换设备前到期时间"),
                ),
                (
                    "expires_after",
                    models.DateTimeField(verbose_name="换设备后到期时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="换设备时间"
                    ),
                ),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_logs",
                        to="keys.licensekey",
                        verbose_name="key",
                    ),
                ),
            ],
            options={
                "verbose_name": "换设备记录",
                "verbose_name_plural": "换设备记录",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
