# Generated by Django 5.2.17 on 2026-09-29 15:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=64, unique=True, verbose_name="标识"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="名称")),
                (
                    "allow_transfer",
                    models.BooleanField(default=False, verbose_name="允许换设备"),
                ),
                (
                    "transfer_penalty_hours",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 表示换设备不扣除时长；1 天填 24",
                        verbose_name="换设备扣减时长（小时）",
                    ),
                ),
                ("disabled", models.BooleanField(default=False, verbose_name="禁用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "软件（product）",
                "verbose_name_plural": "软件（product）",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Activation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=255, unique=True, verbose_name="卡密"),
                ),
                (
                    "device_hash",
                    models.CharField(max_length=64, verbose_name="设备指纹"),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="设备信息"
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="有效时长（天）",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="到期时间")),
                ("disabled", models.BooleanField(default=False, verbose_name="禁用")),
                ("activated_at", models.DateTimeField(verbose_name="激活时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activations",
                        to="keys.product",
                        verbose_name="所属软件",
                    ),
                ),
            ],
            options={
                "verbose_name": "激活记录",
                "verbose_name_plural": "激活记录",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SigningKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_id",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="批次标识"
                    ),
                ),
                ("private_pem", models.TextField(verbose_name="私钥 PEM")),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="卡密有效时长（天）",
                    ),
                ),
                ("count", models.PositiveIntegerField(verbose_name="生成数量")),
                ("disabled", models.BooleanField(default=False, verbose_name="禁用")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="生成时间"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signing_keys",
                        to="keys.product",
                        verbose_name="所属软件",
                    ),
                ),
            ],
            options={
                "verbose_name": "私钥批次",
                "verbose_name_plural": "私钥批次",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_device_hash",
                    models.CharField(max_length=64, verbose_name="旧设备指纹"),
                ),
                (
                    "old_device_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="旧设备信息"
                    ),
                ),
                (
                    "new_device_hash",
                    models.CharField(max_length=64, verbose_name="新设备指纹"),
                ),
                (
                    "new_device_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="新设备信息"
                    ),
                ),
                (
                    "penalty_hours",
                    models.PositiveIntegerField(verbose_name="扣减时长（小时）"),
                ),
                (
                    "expires_before",
                    models.DateTimeField(verbose_name="换设备前到期时间"),
                ),
                (
                    "expires_after",
                    models.DateTimeField(verbose_name="换设备后到期时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="换设备时间"
                    ),
                ),
                (
                    "activation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_logs",
                        to="keys.activation",
                        verbose_name="激活记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "换设备记录",
                "verbose_name_plural": "换设备记录",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
