# Generated by Django 5.2.17 on 2026-10-07 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="kind",
            field=models.CharField(
                choices=[("device", "设备激活"), ("one_time", "一次性")],
                default="device",
                max_length=16,
                verbose_name="类型",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="duration_days",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="卡密有效时长（天）",
            ),
        ),
    ]
