# Generated by Django 5.2.17 on 2026-10-07 12:10

import django.core.validators
from django.db import migrations, models


def one_time_to_count(apps, schema_editor):
    Product = apps.get_model("keys", "Product")
    Batch = apps.get_model("keys", "Batch")
    Product.objects.filter(kind="one_time").update(kind="count")
    Batch.objects.filter(product__kind="count", uses__isnull=True).update(uses=1)


class Migration(migrations.Migration):

    dependencies = [
        ("keys", "0002_product_kind_alter_batch_duration_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="uses",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="每个卡密可用次数",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="kind",
            field=models.CharField(
                choices=[("device", "设备激活"), ("count", "按次数")],
                default="device",
                max_length=16,
                verbose_name="类型",
            ),
        ),
        migrations.RunPython(one_time_to_count, migrations.RunPython.noop),
    ]
